### ISSUE TITLE
Map specific issues (locked maps, end detection, moving platforms on spawn, etc)

### ISSUE THREAD

**Issue by luttje** [Lexicality/slide#1]
With silly blockers, they can be removed with :Remove() just fine, but after that there's some more disabling stuff

I'll see if I can pick this up this month

**Comment by Lexicality** [comment]
There are also maps like `slide_collapse` that become unplayable once someone completes them that need sorting out somehow too.

There's definitely going to need to be more stuff in the `mapfixes` dir, from parenting some spawn points to the moving platforms they're on to adding the ability to pause respawning until everyone dies and then running `game.CleanupMap()`.

We need a proper way of detecting when a player gets to the end stage, as they'll just be trapped in some cases.

**Comment by luttje** [comment]
Notes on `slide_speedrace_v4_1v1_f3` and `slide_shoxx_vs_nitro_f2`:

- `func_wall` at spawn are named `gumpprotect`
- There's a `trigger_teleport` at spawn that moves a player to `desti_buguser`, this points to a filter `ctfilter` (on the `info_player_terrorist` spawn). I imagine this bugs out a user who has hacked their way into the opposite team spawn
- Outside of spawn on the racetrack there's `func_brush` playerclip named `gumblocker`, `noobweg` blocking further passage
- There's a `trigger_hurt` at the end which gives `-200` damage (so heals?)
- There's a `trigger_hurt` directly after that which which gives `100` damage
- The `tfilter` points to a `Negated` `filter_activator_team` which filters `teamnum` 2 (terrorists)
- `ctfilter` does the same but for `teamnum` 3 (counter terrorists)
- `filter_only_ct` and `filter_only_t` are not-negated and so target those teams directly (sometimes called `t_only`, `ct_only`) - As long as `filter_activator_team` keeps working and the teams remain numbers 2 (t) and 3 (ct) we need to do nothing with this info

These maps do the same, except for the protection: `slide_catapult_b1` 

So it seems the first -200, then 100 damage is a good indicator we've finished?

**Comment by luttje** [comment]
Notes on `slide_bounce_f1`:
- There's a `func_movelinear` directly beneath the spawnpoints. So map load all spawnpoints should be parented _if_ a move linear is traced down directly below it
- Another `gumpprotect` `func_wall` and `gumblocker`, `noobweg` `func_brush`
- Ofcourse this map ruins my theory that -200 damage trigger hurt indicates the end:
![image](https://user-images.githubusercontent.com/2738114/95179046-697f5580-07c0-11eb-8221-a01803f23626.png)
Though I found that this map, as well as the other maps do -200 damage at the end, almost directly followed by 100 damage.

**Comment by luttje** [comment]
On `slide_speedrace_v4_1v1_f3` there's this teleporter which brings players into the last trigger again -.-"

![image](https://user-images.githubusercontent.com/2738114/96366101-ae52a700-1145-11eb-951c-7246bc4e32e6.png)

```
Teleported!	Player [1][joker]	Entity [918][trigger_teleport]	2272
PUSH!	Player [1][joker]	Entity [170][trigger_push]	1396
PUSH!	Player [1][joker]	Entity [441][trigger_push]	1710
ServerLog: You received 7 tokens for finishing the map
Healed!	Player [1][joker]	Entity [479][trigger_hurt]	1750
PUSH!	Player [1][joker]	Entity [476][trigger_push]	1747
You received 7 tokens for finishing the map
joker Just finished!
PUSH!	Player [1][joker]	Entity [813][trigger_push]	2159
PUSH!	Player [1][joker]	Entity [919][trigger_push]	2273
Teleported!	Player [1][joker]	Entity [918][trigger_teleport]	2272
PUSH!	Player [1][joker]	Entity [170][trigger_push]	1396
PUSH!	Player [1][joker]	Entity [441][trigger_push]	1710
Healed!	Player [1][joker]	Entity [479][trigger_hurt]	1750
ServerLog: You received 7 tokens for finishing the map
You received 7 tokens for finishing the map
joker Just finished!
PUSH!	Player [1][joker]	Entity [476][trigger_push]	1747
PUSH!	Player [1][joker]	Entity [813][trigger_push]	2159
PUSH!	Player [1][joker]	Entity [919][trigger_push]	2273
Teleported!	Player [1][joker]	Entity [918][trigger_teleport]	2272
PUSH!	Player [1][joker]	Entity [170][trigger_push]	1396
PUSH!	Player [1][joker]	Entity [441][trigger_push]	1710
Healed!	Player [1][joker]	Entity [479][trigger_hurt]	1750
ServerLog: You received 7 tokens for finishing the map
You received 7 tokens for finishing the map
joker Just finished!
```

**Comment by Lexicality** [comment]
I'm currently working on a state machine thingy to solve this sort of problem. So once you've finished the map you're done until you unfinish it by dying or restarting

**Comment by Lexicality** [comment]
ok I think everything here is covered or in a new issue
